name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # 手動実行も可能にする

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
          DISABLE_ESLINT_PLUGIN: 'true'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
